### ISSUE TITLE
Undefined `sample` flag in the subcommand `compile`

### ISSUE THREAD

**Issue by algomaster99** [accordproject/cicero#524]
**Describe the bug**
I tried to generate code using 
```
./packages/cicero-cli/index.js compile --template helloworld@0.12.0.cta --target Typescript
```
But unfortunately, it throws an error `error: A text/sample.md file is required. Try the --sample flag or create a text/sample.md in your template`.
But reading the [documentation](A text/sample.md file is required. Try the --sample flag or create a text/sample.md in your template) and the code, I noticed that this subcommand doesn't have any `sample` flag defined.

**To Reproduce**
1. Run `./packages/cicero-cli/index.js compile --template helloworld@0.12.0.cta`

**Expected behavior**
It shouldn't require a `sample.md` file.

**Screenshots**
![Screenshot from 2020-03-19 13-25-25](https://user-images.githubusercontent.com/35191225/77044283-235dd280-69e5-11ea-98dd-f18bb9650908.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version: On master branch

**Additional context**

**Comment by jeromesimeon** [comment]
Good catch. Thanks @algomaster99

**Comment by jeromesimeon** [comment]
I am not sure why we aren't using the sample in the template when passing an archive (TODO: double check whether the sample is mandatory in a template).

**Comment by algomaster99** [comment]
@jeromesimeon Logically it shouldn't be, right?

**Comment by jeromesimeon** [comment]
@algomaster99 This should now be fixed in Cicero `0.21.2` https://github.com/accordproject/cicero/releases/tag/v0.21.2

Let me know if this works and if we can close.

**Comment by Cronus1007** [comment]
@jeromesimeon This issue still exists in this version as well so shall I start to work upon this issue.
